<a href="https://colab.research.google.com/github/Rajaanthonysamy/PyTorch/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np

torch.__version__

'2.8.0+cu126'

In [ ]:
!nvidia-smi

Wed Sep  3 15:23:15 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

## Vector

In [ ]:
vector= torch.tensor([1,2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix= torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
matrix.shape

torch.Size([2, 3])

In [ ]:
matrix.ndim

2

In [ ]:
tnsr=torch.tensor([[[1,2,3],[4,5,2]]])

In [ ]:
tnsr.shape

torch.Size([1, 2, 3])

In [ ]:
tnsr.ndim

3

In [ ]:
tnsr[0]

tensor([[1, 2, 3],
        [4, 5, 2]])

In [ ]:
tnsr[0][0][0]

tensor(1)

### Random Tensors


Random tensors are important bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [ ]:
torch.rand(3,4)

tensor([[0.9009, 0.8551, 0.1198, 0.9569],
        [0.5474, 0.1775, 0.8059, 0.9399],
        [0.3005, 0.3693, 0.3478, 0.1142]])

In [ ]:
torch.rand(size=(3,4))

tensor([[0.8866, 0.7302, 0.7433, 0.8434],
        [0.8612, 0.2613, 0.1459, 0.5665],
        [0.0976, 0.1790, 0.4067, 0.8524]])

In [ ]:
torch.rand(2,3,3)

tensor([[[0.8298, 0.9176, 0.9595],
         [0.5320, 0.7718, 0.7284],
         [0.4948, 0.5123, 0.8354]],

        [[0.6838, 0.3065, 0.0184],
         [0.0844, 0.9593, 0.6529],
         [0.3719, 0.2280, 0.7082]]])

In [ ]:
## img size random

img_tnsr= torch.rand(size=(3,224,225))
img_tnsr.shape, img_tnsr.ndim

(torch.Size([3, 224, 225]), 3)

In [ ]:
rand_tensor=torch.rand(size=(3,4))
zoroes= torch.zeros(size=(3,4))

In [ ]:
rand_tensor * zoroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
rand_tensor=torch.rand(size=(3,4))
ones= torch.ones(size=(3,4))

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [ ]:
fo_like=torch.arange(1,11,2)

In [ ]:
ten_zeros= torch.zeros_like(fo_like)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0])

In [ ]:
flt_64_tnsr=torch.tensor([3.9,4.754980934,23.22345],
             device='cuda',
             dtype=torch.float64)

flt_64_tnsr.dtype

torch.float64

In [ ]:
flt_32_tnsr= flt_64_tnsr.type(torch.float32)
flt_32_tnsr.dtype

torch.float32

In [ ]:
flt_16_tnsr= flt_64_tnsr.type(torch.float16)


In [ ]:
multi=flt_32_tnsr * flt_16_tnsr

In [ ]:
multi.dtype

torch.float32

In [ ]:
int_32_tnsr= torch.tensor([1,2,3],dtype=torch.int32,device='cuda')

In [ ]:
flt_16_tnsr*int_32_tnsr

tensor([ 3.9004,  9.5078, 69.6250], device='cuda:0', dtype=torch.float16)

# Manipulating Tensors

In [ ]:
tensor= torch.tensor([1,2,3,4])
tensor+100

tensor([101, 102, 103, 104])

In [ ]:
tensor*100

tensor([100, 200, 300, 400])

In [ ]:
tensor-10

tensor([-9, -8, -7, -6])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30, 40])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13, 14])

In [ ]:
torch.sub(tensor,1
          )

tensor([0, 1, 2, 3])

# Matrix Multiplication

In [ ]:
tensor= torch.tensor([1,2,3,4,5])
ele_wise_mul=tensor*tensor
ele_wise_mul

tensor([ 1,  4,  9, 16, 25])

In [ ]:
## Matrix mul
torch.matmul(tensor,tensor)


tensor(55)

In [ ]:
tensor.shape

torch.Size([5])

In [ ]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.6068, 0.5979, 0.6214],
        [0.5620, 0.6815, 0.5610],
        [0.4303, 0.6627, 0.4137]])

In [ ]:
tensor_A= torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
tensor_B=torch.tensor([[4,5,6]])

In [ ]:
tensor_A*tensor_B

tensor([[ 4, 10, 18],
        [16, 25, 36]])

In [ ]:
tensor_A.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## Finding min max mean aggregation



In [ ]:
tensor= torch.arange(10,110,10)

In [ ]:
tensor

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
torch.min(tensor)

tensor(10)

In [ ]:
tensor.min()

tensor(10)

In [ ]:
tensor.max()

tensor(100)

In [ ]:
torch.max(tensor)

tensor(100)

In [ ]:
torch.mean(tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(tensor.type(torch.float32))

tensor(55.)

In [ ]:
tensor.argmin()

tensor(0)

In [ ]:
tensor.argmax()

tensor(9)

In [ ]:
tensors=torch.arange(1,10)

In [ ]:
tensors.size()

torch.Size([9])

In [ ]:
tensor.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 10

In [ ]:
tensors.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
tensors.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
z=tensors.view(1,9)

In [ ]:
tensors,z

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [ ]:
z[:,5]=9999

In [ ]:
z,tensors
x=tensors

In [ ]:
tensors_stacked= torch.stack([x,x,x,x,x,x],dim=0)
tensors_stacked

tensor([[   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9]])

In [ ]:
tensors_stacked= torch.stack([x,x,x,x,x,x],dim=1)
tensors_stacked

tensor([[   1,    1,    1,    1,    1,    1],
        [   2,    2,    2,    2,    2,    2],
        [   3,    3,    3,    3,    3,    3],
        [   4,    4,    4,    4,    4,    4],
        [   5,    5,    5,    5,    5,    5],
        [9999, 9999, 9999, 9999, 9999, 9999],
        [   7,    7,    7,    7,    7,    7],
        [   8,    8,    8,    8,    8,    8],
        [   9,    9,    9,    9,    9,    9]])

In [ ]:
x

tensor([   1,    2,    3,    4,    5, 9999,    7,    8,    9])

In [ ]:
tensors=torch.tensor([[1,2,3,4]])
tensors.size()

torch.Size([1, 4])

In [ ]:
squeeed=tensors.squeeze()

In [ ]:
squeeed.size()

torch.Size([4])

In [ ]:
squeeed.unsqueeze(dim=0)

tensor([[1, 2, 3, 4]])

In [ ]:
squeeed.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
torch.randn(2,3,5)

tensor([[[ 0.4077, -0.1176,  1.0295, -0.2945,  1.1355],
         [ 0.4370, -0.4076,  0.2319,  0.1170,  0.8262],
         [-0.6705,  1.1512, -0.7946, -1.3151, -0.2387]],

        [[-0.0243, -1.0471,  0.8709,  0.4074,  0.9549],
         [ 0.1968,  1.1351, -1.0707,  0.0942, -0.3922],
         [-0.3540,  2.3224,  0.2743,  1.3674,  0.6480]]])

In [ ]:
x_original= torch.randn(224,224,3)

In [ ]:
x_original.permute(2,0,1)
x_original.size()

torch.Size([224, 224, 3])

In [ ]:
x_index= torch.arange(1,11)
x_index

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x_index.reshape(5,2,1)

tensor([[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]],

        [[ 7],
         [ 8]],

        [[ 9],
         [10]]])

In [ ]:
x_index= torch.arange(1,10)
x_index

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_index=x_index.reshape(1,3,3)

In [ ]:
x_index

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x_index[:,:1,1]

tensor([[2]])

In [ ]:
x_index.flip(dims=[2])

tensor([[[3, 2, 1],
         [6, 5, 4],
         [9, 8, 7]]])

In [ ]:
x_index.flip(dims=[1])

tensor([[[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]]])

In [ ]:
x_index[:,:3,2:]

tensor([[[3],
         [6],
         [9]]])

In [ ]:
x_index[:,0:3,1:2]

tensor([[[2],
         [5],
         [8]]])

In [ ]:
x_index[:,:3,:1]

tensor([[[1],
         [4],
         [7]]])

In [ ]:
x_index[:,:2,:]

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
x_index

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1,8)
tensor=torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
tensors=torch.rand(1,10)
tensors

tensor([[0.8530, 0.4468, 0.2027, 0.8690, 0.0521, 0.3346, 0.2438, 0.8127, 0.6235,
         0.2609]])

In [ ]:
tensors.numpy()

array([[0.85301036, 0.44678903, 0.20268524, 0.8689544 , 0.05214179,
        0.3346405 , 0.24382359, 0.8127235 , 0.62352383, 0.26088363]],
      dtype=float32)

In [ ]:
rand_a_tens= torch.rand(3,4)
rand_b_tens= torch.rand(3,4)

print(rand_a_tens==rand_b_tens)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

rand_a_tens= torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_b_tens= torch.rand(3,4)

print(rand_a_tens==rand_b_tens)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [124]:
torch.cuda.is_available()

True

In [125]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [126]:
device

'cuda'

In [128]:
torch.cuda.device_count()

1

"converting the tensors to numpy wont be happen on the GPU so first convert into the cpu then convert to numpy"

In [132]:
tensors=torch.tensor([1,2,3,4,5],device="cuda")
tensors.dtype

torch.int64

In [133]:
tensors.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [134]:
gpu_to_cpu_to_convert_numpy= tensors.cpu().numpy()

In [135]:
tensors

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [136]:
gpu_to_cpu_to_convert_numpy

array([1, 2, 3, 4, 5])

# Excercise

In [140]:
tensors= torch.rand(7,7)

In [141]:
tensors

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [142]:
tensor_a= torch.rand(1,7)
tensor_b= torch.rand(1,7)

In [148]:
torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x7 and 1x7)

In [150]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[1.3799]])

In [151]:
RANDOM_SEED= 0
torch.manual_seed(RANDOM_SEED)
tensor_a= torch.rand(1,7)
torch.manual_seed(RANDOM_SEED)
tensor_b= torch.rand(1,7)

torch.matmul(tensor_a,tensor_b.T)

tensor([[1.5985]])

In [154]:
RANDOM_SEED= 0
torch.cuda.manual_seed_all(RANDOM_SEED)
tensor_a= torch.rand(1,7)
torch.cuda.manual_seed_all(RANDOM_SEED)
tensor_b= torch.rand(1,7)

torch.matmul(tensor_a,tensor_b.T)

tensor([[1.4061]])

In [157]:
RANDOMSEED=1234
torch.cuda.manual_seed(RANDOMSEED)
rand_tensor_a= torch.rand(2,3,device="cuda")
torch.cuda.manual_seed(RANDOMSEED)
rand_tensor_b= torch.rand(2,3,device="cuda")


rand_tensor_a==rand_tensor_b


tensor([[True, True, True],
        [True, True, True]], device='cuda:0')

In [159]:
output=torch.matmul(rand_tensor_a,rand_tensor_b.T)

In [160]:
torch.max(output)


tensor(1.4578, device='cuda:0')

In [161]:
torch.min(output)

tensor(0.8358, device='cuda:0')

In [162]:
torch.argmax(output)

tensor(3, device='cuda:0')

In [163]:
torch.argmin(output)

tensor(1, device='cuda:0')

In [169]:
sq_tensr=torch.rand(1,1,1,10)

In [170]:
sq_tensr

tensor([[[[0.8500, 0.3203, 0.9217, 0.6808, 0.5633, 0.4963, 0.4012, 0.5627,
           0.3858, 0.4965]]]])

In [172]:
sq_tensr.squeeze()[0]

tensor(0.8500)