<a href="https://colab.research.google.com/github/Rajaanthonysamy/PyTorch/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np

torch.__version__

'2.8.0+cu126'

In [2]:
!nvidia-smi

Tue Sep  2 16:22:11 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

## Vector

In [6]:
vector= torch.tensor([1,2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix= torch.tensor([[1,2,3],[4,5,6]])

In [10]:
matrix.shape

torch.Size([2, 3])

In [11]:
matrix.ndim

2

In [12]:
tnsr=torch.tensor([[[1,2,3],[4,5,2]]])

In [13]:
tnsr.shape

torch.Size([1, 2, 3])

In [14]:
tnsr.ndim

3

In [15]:
tnsr[0]

tensor([[1, 2, 3],
        [4, 5, 2]])

In [16]:
tnsr[0][0][0]

tensor(1)

### Random Tensors


Random tensors are important bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [17]:
torch.rand(3,4)

tensor([[0.3611, 0.1677, 0.8705, 0.1871],
        [0.9007, 0.2361, 0.9423, 0.0606],
        [0.9173, 0.4078, 0.5222, 0.2673]])

In [18]:
torch.rand(size=(3,4))

tensor([[0.1321, 0.9394, 0.0048, 0.2172],
        [0.4485, 0.3501, 0.8943, 0.4094],
        [0.9227, 0.2654, 0.8269, 0.9635]])

In [19]:
torch.rand(2,3,3)

tensor([[[0.4553, 0.1842, 0.2644],
         [0.0751, 0.3072, 0.8092],
         [0.8328, 0.4790, 0.7246]],

        [[0.5618, 0.6100, 0.1390],
         [0.0259, 0.5160, 0.8591],
         [0.3473, 0.1203, 0.0498]]])

In [20]:
## img size random

img_tnsr= torch.rand(size=(3,224,225))
img_tnsr.shape, img_tnsr.ndim

(torch.Size([3, 224, 225]), 3)

In [21]:
rand_tensor=torch.rand(size=(3,4))
zoroes= torch.zeros(size=(3,4))

In [22]:
rand_tensor * zoroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
rand_tensor=torch.rand(size=(3,4))
ones= torch.ones(size=(3,4))

In [24]:
ones.dtype

torch.float32

In [25]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [26]:
fo_like=torch.arange(1,11,2)

In [27]:
ten_zeros= torch.zeros_like(fo_like)

In [28]:
ten_zeros

tensor([0, 0, 0, 0, 0])

In [29]:
flt_64_tnsr=torch.tensor([3.9,4.754980934,23.22345],
             device='cuda',
             dtype=torch.float64)

flt_64_tnsr.dtype

torch.float64

In [30]:
flt_32_tnsr= flt_64_tnsr.type(torch.float32)
flt_32_tnsr.dtype

torch.float32

In [31]:
flt_16_tnsr= flt_64_tnsr.type(torch.float16)


In [32]:
multi=flt_32_tnsr * flt_16_tnsr

In [33]:
multi.dtype

torch.float32

In [34]:
int_32_tnsr= torch.tensor([1,2,3],dtype=torch.int32,device='cuda')

In [35]:
flt_16_tnsr*int_32_tnsr

tensor([ 3.9004,  9.5078, 69.6250], device='cuda:0', dtype=torch.float16)

# Manipulating Tensors

In [36]:
tensor= torch.tensor([1,2,3,4])
tensor+100

tensor([101, 102, 103, 104])

In [37]:
tensor*100

tensor([100, 200, 300, 400])

In [38]:
tensor-10

tensor([-9, -8, -7, -6])

In [39]:
torch.mul(tensor,10)

tensor([10, 20, 30, 40])

In [40]:
torch.add(tensor,10)

tensor([11, 12, 13, 14])

In [41]:
torch.sub(tensor,1
          )

tensor([0, 1, 2, 3])

# Matrix Multiplication

In [42]:
tensor= torch.tensor([1,2,3,4,5])
ele_wise_mul=tensor*tensor
ele_wise_mul

tensor([ 1,  4,  9, 16, 25])

In [43]:
## Matrix mul
torch.matmul(tensor,tensor)


tensor(55)

In [44]:
tensor.shape

torch.Size([5])

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.3404, 0.3973, 0.1399],
        [0.4572, 0.5333, 0.1879],
        [0.6449, 0.7611, 0.2653]])

In [46]:
tensor_A= torch.tensor([[1,2,3],[4,5,6]])

In [47]:
tensor_B=torch.tensor([[4,5,6]])

In [48]:
tensor_A*tensor_B

tensor([[ 4, 10, 18],
        [16, 25, 36]])

In [49]:
tensor_A.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## Finding min max mean aggregation



In [50]:
tensor= torch.arange(10,110,10)

In [51]:
tensor

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [52]:
torch.min(tensor)

tensor(10)

In [53]:
tensor.min()

tensor(10)

In [54]:
tensor.max()

tensor(100)

In [55]:
torch.max(tensor)

tensor(100)

In [56]:
torch.mean(tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [57]:
torch.mean(tensor.type(torch.float32))

tensor(55.)

In [58]:
tensor.argmin()

tensor(0)

In [59]:
tensor.argmax()

tensor(9)

In [60]:
tensors=torch.arange(1,10)

In [61]:
tensors.size()

torch.Size([9])

In [62]:
tensor.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 10

In [63]:
tensors.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [64]:
tensors.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [65]:
z=tensors.view(1,9)

In [66]:
tensors,z

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [67]:
z[:,5]=9999

In [68]:
z,tensors
x=tensors

In [69]:
tensors_stacked= torch.stack([x,x,x,x,x,x],dim=0)
tensors_stacked

tensor([[   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9],
        [   1,    2,    3,    4,    5, 9999,    7,    8,    9]])

In [70]:
tensors_stacked= torch.stack([x,x,x,x,x,x],dim=1)
tensors_stacked

tensor([[   1,    1,    1,    1,    1,    1],
        [   2,    2,    2,    2,    2,    2],
        [   3,    3,    3,    3,    3,    3],
        [   4,    4,    4,    4,    4,    4],
        [   5,    5,    5,    5,    5,    5],
        [9999, 9999, 9999, 9999, 9999, 9999],
        [   7,    7,    7,    7,    7,    7],
        [   8,    8,    8,    8,    8,    8],
        [   9,    9,    9,    9,    9,    9]])

In [71]:
x

tensor([   1,    2,    3,    4,    5, 9999,    7,    8,    9])

In [72]:
tensors=torch.tensor([[1,2,3,4]])
tensors.size()

torch.Size([1, 4])

In [74]:
squeeed=tensors.squeeze()

In [75]:
squeeed.size()

torch.Size([4])

In [77]:
squeeed.unsqueeze(dim=0)

tensor([[1, 2, 3, 4]])

In [78]:
squeeed.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3],
        [4]])

In [81]:
torch.randn(2,3,5)

tensor([[[-0.2362, -0.2138,  1.0084,  1.1675,  0.2282],
         [-0.9086, -1.4407,  1.7243,  0.7869,  0.2652],
         [-0.1273, -1.8848,  0.3220, -0.0871, -0.5971]],

        [[-1.0235,  0.2595,  1.2902,  1.0767,  2.9007],
         [-0.3447,  1.4168, -0.3726, -0.9265, -0.9118],
         [-0.2387,  0.5866,  0.0313, -1.3418,  0.3388]]])

In [82]:
x_original= torch.randn(224,224,3)

In [87]:
x_original.permute(2,0,1)
x_original.size()

torch.Size([224, 224, 3])

In [100]:
x_index= torch.arange(1,11)
x_index

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
x_index.reshape(5,2,1)

tensor([[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]],

        [[ 7],
         [ 8]],

        [[ 9],
         [10]]])

In [112]:
x_index= torch.arange(1,10)
x_index

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
x_index=x_index.reshape(1,3,3)

In [126]:
x_index

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [128]:
x_index[:,:1,1]

tensor([[2]])

In [134]:
x_index.flip(dims=[2])

tensor([[[3, 2, 1],
         [6, 5, 4],
         [9, 8, 7]]])

In [135]:
x_index.flip(dims=[1])

tensor([[[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]]])