<a href="https://colab.research.google.com/github/Rajaanthonysamy/PyTorch/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np

torch.__version__

'2.8.0+cu126'

In [2]:
!nvidia-smi

Mon Sep  1 14:59:10 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
scalar= torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

## Vector

In [6]:
vector= torch.tensor([1,2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix= torch.tensor([[1,2,3],[4,5,6]])

In [10]:
matrix.shape

torch.Size([2, 3])

In [11]:
matrix.ndim

2

In [12]:
tnsr=torch.tensor([[[1,2,3],[4,5,2]]])

In [13]:
tnsr.shape

torch.Size([1, 2, 3])

In [14]:
tnsr.ndim

3

In [15]:
tnsr[0]

tensor([[1, 2, 3],
        [4, 5, 2]])

In [16]:
tnsr[0][0][0]

tensor(1)

### Random Tensors


Random tensors are important bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [17]:
torch.rand(3,4)

tensor([[0.8860, 0.2818, 0.7845, 0.1312],
        [0.8075, 0.6757, 0.0985, 0.8714],
        [0.7988, 0.3264, 0.8637, 0.2772]])

In [18]:
torch.rand(size=(3,4))

tensor([[0.1385, 0.5623, 0.8513, 0.2174],
        [0.6743, 0.9940, 0.1951, 0.9117],
        [0.7335, 0.1918, 0.7303, 0.5084]])

In [19]:
torch.rand(2,3,3)

tensor([[[0.2853, 0.4816, 0.4596],
         [0.0498, 0.4752, 0.9929],
         [0.6917, 0.5087, 0.1146]],

        [[0.7024, 0.7464, 0.5483],
         [0.3661, 0.9949, 0.4253],
         [0.5707, 0.0590, 0.8858]]])

In [20]:
## img size random

img_tnsr= torch.rand(size=(3,224,225))
img_tnsr.shape, img_tnsr.ndim

(torch.Size([3, 224, 225]), 3)

In [21]:
rand_tensor=torch.rand(size=(3,4))
zoroes= torch.zeros(size=(3,4))

In [22]:
rand_tensor * zoroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
rand_tensor=torch.rand(size=(3,4))
ones= torch.ones(size=(3,4))

In [24]:
ones.dtype

torch.float32

In [25]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [26]:
fo_like=torch.arange(1,11,2)

In [27]:
ten_zeros= torch.zeros_like(fo_like)

In [28]:
ten_zeros

tensor([0, 0, 0, 0, 0])

In [29]:
flt_64_tnsr=torch.tensor([3.9,4.754980934,23.22345],
             device='cuda',
             dtype=torch.float64)

flt_64_tnsr.dtype

torch.float64

In [30]:
flt_32_tnsr= flt_64_tnsr.type(torch.float32)
flt_32_tnsr.dtype

torch.float32

In [31]:
flt_16_tnsr= flt_64_tnsr.type(torch.float16)


In [32]:
multi=flt_32_tnsr * flt_16_tnsr

In [33]:
multi.dtype

torch.float32

In [36]:
int_32_tnsr= torch.tensor([1,2,3],dtype=torch.int32,device='cuda')

In [37]:
flt_16_tnsr*int_32_tnsr

tensor([ 3.9004,  9.5078, 69.6250], device='cuda:0', dtype=torch.float16)

# Manipulating Tensors

In [39]:
tensor= torch.tensor([1,2,3,4])
tensor+100

tensor([101, 102, 103, 104])

In [40]:
tensor*100

tensor([100, 200, 300, 400])

In [41]:
tensor-10

tensor([-9, -8, -7, -6])

In [42]:
torch.mul(tensor,10)

tensor([10, 20, 30, 40])

In [43]:
torch.add(tensor,10)

tensor([11, 12, 13, 14])

In [44]:
torch.sub(tensor,1
          )

tensor([0, 1, 2, 3])

# Matrix Multiplication