<a href="https://colab.research.google.com/github/Rajaanthonysamy/PyTorch/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np

torch.__version__

'2.8.0+cu126'

In [ ]:
!nvidia-smi

Wed Aug 27 16:12:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

## Vector

In [ ]:
vector= torch.tensor([1,2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix= torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
matrix.shape

torch.Size([2, 3])

In [ ]:
matrix.ndim

2

In [ ]:
tnsr=torch.tensor([[[1,2,3],[4,5,2]]])

In [ ]:
tnsr.shape

torch.Size([1, 2, 3])

In [ ]:
tnsr.ndim

3

In [ ]:
tnsr[0]

tensor([[1, 2, 3],
        [4, 5, 2]])

In [ ]:
tnsr[0][0][0]

tensor(1)

### Random Tensors


Random tensors are important bcoz the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [ ]:
torch.rand(3,4)

tensor([[0.7757, 0.2005, 0.9369, 0.5180],
        [0.3410, 0.7587, 0.5095, 0.3567],
        [0.9869, 0.5873, 0.0923, 0.2634]])

In [ ]:
torch.rand(size=(3,4))

tensor([[0.1564, 0.0049, 0.9432, 0.9714],
        [0.3608, 0.8388, 0.2447, 0.5742],
        [0.1741, 0.8693, 0.7480, 0.7701]])

In [ ]:
torch.rand(2,3,3)

tensor([[[0.2094, 0.6989, 0.3886],
         [0.6260, 0.9313, 0.6343],
         [0.1525, 0.3241, 0.0461]],

        [[0.7701, 0.4228, 0.1244],
         [0.7694, 0.0599, 0.1707],
         [0.9357, 0.2265, 0.2691]]])

In [ ]:
## img size random

img_tnsr= torch.rand(size=(3,224,225))
img_tnsr.shape, img_tnsr.ndim

(torch.Size([3, 224, 225]), 3)

In [ ]:
rand_tensor=torch.rand(size=(3,4))
zoroes= torch.zeros(size=(3,4))

In [ ]:
rand_tensor * zoroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
rand_tensor=torch.rand(size=(3,4))
ones= torch.ones(size=(3,4))

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [ ]:
fo_like=torch.arange(1,11,2)

In [ ]:
ten_zeros= torch.zeros_like(fo_like)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0])

In [ ]:
flt_64_tnsr=torch.tensor([3.9,4.754980934,23.22345],
             device='cuda',
             dtype=torch.float64)

flt_64_tnsr.dtype

torch.float64

In [ ]:
flt_32_tnsr= flt_64_tnsr.type(torch.float32)
flt_32_tnsr.dtype

torch.float32